### ISSUE TITLE
Policy for 'extras_require' dependencies

### ISSUE THREAD

**Issue by davidh-ssec** [conda-forge/pyresample-feedstock#17]
What is conda-forge's policy on conda dependencies that are listed under a package's `extras_require` in the setup.py file? Pyresample has a 'quicklook' extra that needs matplotlib, basemap, and pillow. The first two are rather large dependencies that a user is forced to install when they are only really used for debugging. Would it be possible to remove these dependencies from the conda-forge package?

**Comment by ocefpaf** [comment]
We don't have a clear policy but we try to do what is most convenient for the users. If you want to remove those I am OK with it.
